name: Sandbox Deploy
on:
  push:
    branches: [ sandbox ]
jobs:
  build:
    container: node:13
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build:dev --if-present
        working-directory: ./theme
